/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

namespace Astrana.Core.Constants
{
    public static class AnonymousUser
    {
        /// <summary>
        /// This ID should remain unchanged forever.
        /// 
        /// This value was chosen because:
        ///    1.) it is easy to recognize and therefore easier for a human to see when data is generated by an anonymous or unknown human user or process; 
        ///    2.) the Anonymous User is a Pseudo-User that has no corresponding User Account and therefore has no ID, and therefore is represented by zeros; 
        ///    3.) it supports the implementation of the Least Privilege principle by default because its value is the same as the default and empty value of the GUID type
        /// </summary>
        public const string Id = "00000000-0000-0000-0000-000000000000";
        public static readonly Guid IdGuid = Guid.Parse(Id);
    }
}
