/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

namespace Astrana.Core.Constants
{
    public static class SystemUser
    {
        /// <summary>
        /// This ID should remain unchanged forever.
        /// 
        /// This value was chosen because:
        ///    1.) it is easy to recognize and therefore easier for a human to see when data is generated by a system process;
        ///    2.) the System User is the first user and the De facto user before the Instance User is setup and is therefore represented by all one's
        /// </summary>
        public const string Id = "11111111-1111-1111-1111-111111111111";
        public static readonly Guid IdGuid = Guid.Parse(Id);
    }
}
